services:
    fetch_data:
        build:
            context: .
            dockerfile: Dockerfile.fetch_data
        command: python main.py
        environment:
            - TICKER=^NSEI
        volumes:
            - ./data:/fetch_data/data
        restart: on-failure

    lightpanda:
        image: lightpanda/browser:nightly
        restart: unless-stopped
        ports:
            - '9222:9222'

    fetch_news:
        build:
            context: .
            dockerfile: Dockerfile.fetch_news
        volumes:
            - ./data:/app/data/
        depends_on:
            - lightpanda

    test_python:
        build:
            context: .
            dockerfile: Dockerfile.python
        volumes:
            - ./test:/test
        stdin_open: true
        tty: true

    jupyter:
        image: quay.io/jupyter/base-notebook
        ports:
            - 8889:8888
        volumes:
            - ./jupyter-data:/home/jovyan/work
        command: start-notebook.py --NotebookApp.token='my-token'